name: SaaS ETL Pipeline CI/CD

on:
  push:
    branches:
      - main # <--- O erro "No event triggers defined in 'on'" está aqui se essa seção estiver faltando ou mal formatada

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    # AQUI ENTRA A SEÇÃO SERVICES QUE VOCÊ ME MOSTROU
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: ${{ secrets.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup .env variables
      run: |
        echo "DB_TYPE=postgresql" >> .env # Se usar o serviço, o DB_TYPE é sempre postgresql
        echo "DB_HOST=postgres" >> .env  # <--- O HOST AGORA É 'postgres' (o nome do serviço)
        echo "DB_PORT=5432" >> .env       # A porta interna do container
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Run ETL Pipeline
      run: python -m src.main

    - name: Check for new data (Optional - example)
      run: |
        echo "Aguardando verificação de dados carregados..."